Implement Exploratory Daemon
cmu-db/postgres pull request #19
Opened 2021-11-04 18:08 UTC by jkosh44

This commits adds the functionality to take online copies of a
postgres database. The goal of the copy is to be able to run fast
but not necessarily have the most up to date data. The process of
taking a copy is the following:
1. Run checkpoint on original database (This is not strictly
required).
2. Take a ZFS snapshot and clone of pgdata directory.
3. Run pg_resetwal on ZFS copy. This will prune the log to some
consistent point which makes starting the new instance much faster.
However it also results in some lost data.
4. Start exploratory docker container which uses the copied pgdata
directory to start a postgres instance.

The process of tearing down an exploratory instance is the
following:
1. Stop postgres instance.
2. Shutdown docker container.
3. Delete copied data.

The daemon needs to be run on a system with an existing postgres
instance and ZFS installed.

The current implementation just takes a single copy, runs some
random queries, and tears down the copy. In the future this
functionality will be daemonized to allow on demand copies to
be made.

2021-11-04 18:09 UTC, jkosh44 commented on cmudb/exploration/sql.py
> +# SQL functionality
Based on @mkpjnx demo, may want to switch to psycopg package

2021-11-04 18:10 UTC, jkosh44 commented on cmudb/exploration/util.py
> +def execute_sys_command(cmd: Union[str, List[str]],
I have very mixed feelings about wrapping `subprocess.Popen`. On the one hand I find `subprocess.Popen` a bit cumbersome to use by itself. On the other hand it seems like all of our projects wrap the method in slightly different ways, and they often get a bit messy.

2021-11-19 19:45 UTC, lmwnshn commented
For wider publicity: yes, this PR has been sitting out here,

- I am happy with the code as it is, in theory it could merge
- I am currently working on integrating it with something else to see if there are things I would change

2021-11-19 19:50 UTC, jkosh44 commented on cmudb/exploration/exploratory_daemon.py
> +    The exploratory daemon is responsible for creating a copy of replica instances, to be used for model training.
@lmwnshn Is this clear enough or too vague? I didn't want to dump a bunch of commands to run but I also wanted to provide some detail.

2021-11-19 19:50 UTC, jkosh44 commented on cmudb/exploration/exploratory_daemon.py
> +    checkpoint(replica_port)
@lmwnshn I think honestly we should remove this. I'm not really sure how much we gain by calling a checkpoint and it ends up being really expensive a lot of the time.

2021-12-30 00:14 UTC, lmwnshn requested changes
LGTM pending one nit. Thanks for the documentation! will be super helpful

2021-12-30 00:14 UTC, lmwnshn commented on cmudb/build/pgindent.sh
> +#!/bin/bash
Please remove this -- I think we're giving up on `pgindent`.

2021-12-30 00:19 UTC, lmwnshn approved these changes
LGTM.

2021-12-30 00:21 UTC, merged